# Generated by Django 4.2.5 on 2023-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0002_rename_first_name_customuser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('tipo', models.TextField(max_length=100)),
                ('dirrecion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
