# Generated by Django 4.2.5 on 2023-09-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0003_restaurantesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantesmodel',
            old_name='dirrecion',
            new_name='direccion',
        ),
    ]
