# Generated by Django 4.2.5 on 2023-09-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0004_rename_dirrecion_restaurantesmodel_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantesmodel',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
