# Generated by Django 4.2.5 on 2023-09-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0005_alter_restaurantesmodel_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantesmodel',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
