# Generated by Django 4.2.5 on 2023-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0007_alter_restaurantesmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantesmodel',
            name='tipo',
            field=models.TextField(max_length=100),
        ),
    ]
